---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/jamescherti/pre-commit-elisp
    rev: v1.0.0
    hooks:
      - id: elisp-check-parens
      - id: elisp-byte-compile
      - id: elisp-indent
