;;; init.el --- Init -*- lexical-binding: t; -*-

;; Author: James Cherti <https://www.jamescherti.com/contact/>
;; URL: https://github.com/jamescherti/lightemacs
;; Package-Requires: ((emacs "29.1"))
;; Keywords: maint
;; Version: 0.0.9
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Lightemacs is a Fast and Lightweight Emacs Framework.

;;; Code:

;;; Require

;;; Write the automatically generated configuration

(unless (memq lightemacs-package-manager '(straight elpaca builtin-package
                                                    ;; Deprecated:
                                                    use-package))
  (error "The value '%s' is not a valid `lightemacs-package-manager'"
         lightemacs-package-manager))

;;; require

(require 'lightemacs)

;;; Call `lightemacs-user-pre-init'

(when (fboundp 'lightemacs-user-pre-init)
  (lightemacs-user-pre-init))

;;; Load: init.el

(when (and (fboundp 'lightemacs-load-user-init)
           (boundp 'minimal-emacs-user-directory))
  (lightemacs-load-user-init
   (expand-file-name "init.el" minimal-emacs-user-directory)))

;;; Configure the package manager

(defvar lightemacs-use-package--package-manager-loaded nil)

(unless lightemacs-use-package--package-manager-loaded
  (when (bound-and-true-p lightemacs-package-manager)
    (cond
     ;; Straight
     ((eq lightemacs-package-manager 'straight)
      (require 'le-core-pm-straight))

     ;; Elpaca
     ((eq lightemacs-package-manager 'elpaca)
      (require 'le-core-pm-elpaca))

     ;; use-package (built-in)
     ((or (eq lightemacs-package-manager 'builtin-package)
          (eq lightemacs-package-manager 'use-package))
      (require 'le-core-pm-use-package))

     (t
      (error
       (concat "[lightemacs]"
               "Invalid value for `lightemacs-package-manager': '%S'. Valid "
               "choices are: 'straight, 'elpaca, or 'use-package.")
       lightemacs-package-manager))))

  (setq lightemacs-use-package--package-manager-loaded t))

;; Generate loadable config

(defun lightemacs--generate-le-autogen-config ()
  "Generate the Elisp config."
  ;; Load le-autogen-config here
  (let* ((local-dir (expand-file-name "var" lightemacs-core-directory))
         (file-path (expand-file-name "le-autogen-config.el" local-dir)))
    (setenv "LIGHTEMACS__INTERNAL_LOAD_CONFIG" file-path)
    (if (file-exists-p file-path)
        (load file-path nil lightemacs-debug)
      ;; Ensure the local directory exists
      (unless (file-directory-p local-dir)
        (make-directory local-dir t))

      ;; Write the configuration to the file
      (with-temp-file file-path
        (insert ";;; le-autogen-config.el --- Auto-generated "
                "configuration -*- no-byte-compile: t; lexical-binding: t -*-\n\n")
        (insert ";; This file is auto-generated by early-init.el\n\n")
        (insert (format ";; Generated on: %s\n\n" (current-time-string)))

        ;; Package manager
        (insert (format "(setq lightemacs-package-manager '%s)\n\n"
                        (prin1-to-string lightemacs-package-manager)))

        ;; Evil Integration
        (let ((val (if (boundp 'evil-want-integration)
                       evil-want-integration
                     t)))
          (insert (format "(setq evil-want-integration %S)\n" val))
          (setq evil-want-integration val))

        ;; Evil Keybindings
        (let ((val (if (boundp 'evil-want-keybinding)
                       evil-want-keybinding
                     nil)))
          (insert (format "(setq evil-want-keybinding %S)\n\n" val))
          (setq evil-want-keybinding val))

        (insert
         (concat "(when (bound-and-true-p byte-compile-current-file)\n"))

        (insert (format "(setq lightemacs-user-directory %s)\n"
                        (prin1-to-string (abbreviate-file-name
                                          lightemacs-user-directory))))
        (insert (format "(setq lightemacs-local-directory %s)\n"
                        (prin1-to-string (abbreviate-file-name
                                          lightemacs-local-directory))))
        (insert (format "(setq lightemacs-var-directory %s)\n"
                        (prin1-to-string (abbreviate-file-name
                                          lightemacs-var-directory))))
        (insert (format "(setq lightemacs-core-directory %s)\n\n"
                        (prin1-to-string (abbreviate-file-name
                                          lightemacs-core-directory))))

        (when (eq lightemacs-package-manager 'elpaca)
          (insert (concat
                   "(unless (fboundp 'elpaca)\n"
                   "  (let ((lightemacs--no-bootstrap t))\n"
                   "    (load (expand-file-name \"le-core-pm-elpaca.el\"\n"
                   "                            lightemacs-core-directory)\n"
                   "  nil\n"
                   "  'nomessage)))\n\n")))

        (when (eq lightemacs-package-manager 'straight)
          (insert

           (concat
            (format
             "(unless (fboundp 'straight-use-package)\n")
            (format
             "  (setq straight-use-package-by-default %s)\n"
             (if straight-use-package-by-default
                 "t"
               "nil"))
            (format
             (concat
              "  (let ((lightemacs--no-bootstrap t)\n"
              "        (bootstrap-version 7))\n"
              ;; Force the correct directory to avoid ~/.emacs.d/ leaks
              "    (setq user-emacs-directory lightemacs-var-directory)\n"
              "    (setq straight-base-dir lightemacs-var-directory)\n"
              ;; Disable all straight.el modification checks and builds
              "    (setq straight-check-for-modifications nil)\n"
              "    (setq straight-disable-compile t)\n"
              "    (setq straight-disable-native-compile t)\n"
              ;; Load
              "    (load (expand-file-name\n"
              "           \"straight/repos/straight.el/bootstrap.el\"\n"
              "           straight-base-dir)\n"
              "          nil\n"
              "          'nomessage))"))
            (format
             ")\n\n"))))

        ;; use-package optimization
        (let ((val (if (boundp 'use-package-expand-minimally)
                       use-package-expand-minimally
                     t)))
          (insert (format "(setq use-package-expand-minimally %S)\n\n" val))
          (setq use-package-expand-minimally val))

        ;; End byte/native compile only
        (insert "\n)\n\n")

        (insert ";;; le-autogen-config.el ends here\n"))

      ;; TODO
      ;; (lightemacs-debug-message
      ;;   "[lightemacs] Wrote package manager '%s' to %s"
      ;;   lightemacs-package-manager
      ;;   file-path)
      )))

;; Call it first for `lightemacs-package-manager'
(lightemacs--generate-le-autogen-config)


;;; Hook `lightemacs-after-init-hook'

(defun lightemacs--run-after-init-hook ()
  "Run `lightemacs-after-init-hook' at the appropriate time."
  (unwind-protect
      (run-hooks 'lightemacs-after-init-hook)
    (cond
     ((eq lightemacs-package-manager 'elpaca)
      (remove-hook 'elpaca-after-init-hook 'lightemacs--run-after-init-hook))

     (t
      (remove-hook 'after-init-hook 'lightemacs--run-after-init-hook)))))

(defun lightemacs--run-emacs-startup-hook ()
  "Run `lightemacs-emacs-startup-hook' at the appropriate time."
  (unwind-protect
      (run-hooks 'lightemacs-emacs-startup-hook)
    (cond
     ((eq lightemacs-package-manager 'elpaca)
      (remove-hook 'elpaca-after-init-hook 'lightemacs--run-emacs-startup-hook))

     (t
      (remove-hook 'emacs-startup-hook 'lightemacs--run-emacs-startup-hook)))))

(cond
 ((eq lightemacs-package-manager 'elpaca)
  (add-hook 'elpaca-after-init-hook 'lightemacs--run-after-init-hook 104)
  (add-hook 'elpaca-after-init-hook 'lightemacs--run-emacs-startup-hook 105))

 (t
  (add-hook 'after-init-hook 'lightemacs--run-after-init-hook 104)
  (add-hook 'emacs-startup-hook 'lightemacs--run-emacs-startup-hook 105)))

;;; Function: `lightemacs-user-pre-modules'

;; Load function: `lightemacs-user-pre-modules'
(when (fboundp 'lightemacs-user-pre-modules)
  (lightemacs-user-pre-modules))

;;; Load modules

(require 'lightemacs-use-package)
(require 'lightemacs-module)

(if (fboundp 'lightemacs-module-load)
    (progn
      (lightemacs-module-load lightemacs-core-modules)
      (lightemacs-module-load lightemacs-modules))
  (error "Undefined function: lightemacs-module-load"))

;;; Function: `lightemacs-user-post-modules'

;; Load function: `lightemacs-user-post-modules'
(when (fboundp 'lightemacs-user-post-modules)
  (lightemacs-user-post-modules))

;;; Function: `lightemacs-user-init'

(when (fboundp 'lightemacs-user-init)
  (lightemacs-user-init))

;;; Function: `lightemacs-user-post-init'

(when (fboundp 'lightemacs-user-post-init)
  (funcall 'lightemacs-user-post-init))

;;; Provide

(provide 'init)

;; Local variables:
;; byte-compile-warnings: (not obsolete free-vars)
;; End:

;;; init.el ends here
